version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

  server-1:
    build: ./server
    networks:
      - my-network
    environment:
      - SERVER_ID=1
    
  server-2:
    build: ./server
    networks:
      - my-network
    environment:
      - SERVER_ID=2

  server-3:
    build: ./server
    networks:
      - my-network
    environment:
      - SERVER_ID=3

  server-4:
    build: ./server
    networks:
      - my-network
    environment:
      - SERVER_ID=4

networks:
  my-network:
    driver: bridge
  